Fix bug: Parser infinite loop when setting enum value to unclosed bracket
SerenityOS/jakt pull request #254
Opened 2022-05-23 11:36 UTC by cybergsus

Should close #233.

The parser for `parse_array` didn't bail when `parse_expression` failed and it 
could not recover from the error, resulting in an endless loop.

Likewise, `parse_enum` didn't contain a loop itself but the fact that it 
didn't error out when encountering `Eof` when expecting a `}` makes outer-level 
parsers not aware that `Eof` has been reached, which makes them continue their
loops.

The 'infinite loop' problem has been fixed for those two, although it might 
need a second look at `parse_array` or other parsers for enclosed lists to make 
sure they bail if their last token doesn't close the list. However, the errors 
that get spit out don't match with the actual error that happened, so please 
don't merge this until that problem is solved.

Another problem that occurs to me is that I don't know how to test this,
since checking that an infinite loop doesn't happen is not trivial, or at least
I haven't been able to think of a good solution. Help there will be appreciated.

2022-05-23 11:50 UTC, linusg requested changes
> Another problem that occurs to me is that I don't know how to test this, since checking that an infinite loop doesn't happen is not trivial, or at least I haven't been able to think of a good solution. Help there will be appreciated.

It is trivial - just add a test for the expected output, and if it never completes, it fails.

`bug:` is not a valid prefix, please use `parser:` and remove the merge commits.

2022-05-23 11:50 UTC, linusg commented on src/parser.rs
> +                    return (ParsedExpression::OptionalNone(tokens[*index].span), err);
```suggestion
                    return (ParsedExpression::Garbage(tokens[*index].span), err);
```

2022-05-23 11:52 UTC, cybergsus commented
Ok. How do I remove those merge commits?

2022-05-23 11:54 UTC, linusg commented
look up how `git rebase` works, there's plenty of information on that out there

2022-05-23 12:59 UTC, cybergsus commented
Parser tests pass, but rest of tests currently fail. I'll be fixing those

2022-05-23 13:11 UTC, cybergsus commented
Looks like all the tests pass right now.

2022-05-23 18:24 UTC, cybergsus commented
It currently fails since `ref` was not yet implemented when I forked. How do I get those changes here?

2022-05-23 21:29 UTC, Lubrsi commented
In case you haven't already, you will have to add the base repo as a remote:
```
git remote add upstream https://github.com/SerenityOS/jakt.git
```
Then, fetch upstream:
```
git fetch upstream
```
Then, whilst on your branch, perform:
```
git rebase upstream/main
```

2022-05-23 21:33 UTC, cybergsus commented
Ok, now it runs. I'm now running the whole test suite to know if I messed up somewhere else.

2022-05-23 21:34 UTC, cybergsus commented
![image](https://user-images.githubusercontent.com/54634335/169909476-84e2b0dc-14e7-4c4a-b0e9-7f2bb75fae9e.png)
Ok, it works now!

2022-05-23 21:37 UTC, cybergsus commented
I've also walked down the parser code and checked for more possible mishaps regarding reaching EOF in loops, since the lexer emits an extra EOF token and therefore `*index < tokens.len()` remains true if EOF is not handled, and the loop continues unless the function bails on a subparser error.

2022-05-24 10:46 UTC, linusg requested changes
https://github.com/SerenityOS/jakt/blob/master/CONTRIBUTING.md#code-submission-policy

> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

2022-06-01 10:07 UTC, awesomekling commented
This looks like a valuable PR, it just needs a refresh since `ref enum` was renamed to `boxed enum` :)

2022-06-01 18:38 UTC, cybergsus commented
Tests for `test_dictionary` continue failing.
]

2022-06-01 22:26 UTC, merged