typechecker: Added cint type id to negate
SerenityOS/jakt pull request #466
Opened 2022-05-31 21:22 UTC by Lenart12

Before we couldn't typecast negative constants to c_int.
This fix makes it so now we can do things like `-1 as! c_int`.
Fixes #465.

2022-05-31 22:47 UTC, linusg requested changes
https://github.com/SerenityOS/jakt/blob/main/CONTRIBUTING.md#code-submission-policy
> Write the commit message subject line in the imperative mood ("Foo: Change the way dates work", not "Foo: Changed the way dates work").

2022-05-31 22:47 UTC, linusg commented on tests/typechecker/array_negative_c_int.jakt
> +    let array: [c_int] = [-1 as! c_int, -1 as! c_int, 2 as! c_int]
What's the point of doing the same test twice here?

2022-06-01 00:41 UTC, Lenart12 commented
Changed the commit message and changed up the test.
`if array[0] == -1 as! c_int` still feels weird, but atleast its castable now.
Would be cool if we could do just `if array[0] == -1` since casting -1 to c_int would never fail.

2022-06-01 10:48 UTC, linusg commented on tests/typechecker/array_negative_c_int.jakt
> +    if array[0] == -1 as! c_int {
I don't understand why this is needed. Just print `array[0]` unconditionally...?

2022-06-01 10:49 UTC, linusg requested changes
`Adds` is not imperative mood

2022-06-01 11:36 UTC, linusg approved these changes
Thanks!

2022-06-01 11:43 UTC, merged