selhost: Add support for bindings with IS operator
SerenityOS/jakt pull request #957
Opened 2022-07-23 20:30 UTC by adleroliveira

This implements variable bindings for enum variants for both
typed and struct-like variants. It de-sugar variable bindings
into typed optionals + pattern mathing with rebinding of inner
values followed bu a forced unwrap.

Example:

enum Foo {
    Bar(i64)
}

let foo = Foo::Bar(5)

// This:
if foo is Foo::Bar(n) {
    println("{}", n)
}

// De-sugar to this:
mut tmp_n: i64? = None
if foo is Foo::Bar {
    match foo {
        Bar(n) => {
            tmp_n = n
        }
    }
    let n = tmp_n!
    println("{}", n)
}

2022-07-23 20:38 UTC, awesomekling requested changes
Typo: selhost -> selfhost
Typo: IS -> is
Typo: de-sugar -> de-sugars
Typo: bu -> by

The `tmp_n` in the desugared code should be scoped inside the `if` block, not outside it.

2022-07-23 20:43 UTC, jntrnr commented
Oh sweet!

Does `if foo is Foo::Bar(n)` also let you do things like: `if foo is Foo::Bar(n) and n > 100` ?

2022-07-23 21:03 UTC, alimpfard commented on selfhost/typechecker.jakt
> +    function expand_block_bindings(this, anon block: ParsedBlock, checked_condition: CheckedExpression, span: Span) throws -> ParsedBlock {
I'm not quite sure what _precisely_ this desugars to, but you can directly codegen this, no need to involve a match
```
if foo is Bar(x: y) and expr {
    true_branch
}
```
(provided that `foo` is of an enum type)
```c++
if (auto _value = foo.get_pointer<FooDetails::Bar>()) {
    auto& y = _value.x;
    if (codegen.expr) {
        codegen.true_branch;
    }
}
```

for simplicity, `or` could simply be split up into multi `if` statements before entering the codegen stage.

2022-07-23 21:03 UTC, alimpfard commented on selfhost/typechecker.jakt
> +        mut is_enum_exaustive = false
typo: `is_enum_exaustive` -> `is_enum_exhaustive`

2022-07-23 22:06 UTC, adleroliveira commented
Converting it into a Draft while I work no the various comments.

2022-07-25 01:08 UTC, adleroliveira commented on selfhost/parser.jakt
> +    )
Where would be the right place then?

When parsing something like Foo::Bar(a) what is generated is a ParsedType::NamespacedName
This specific enum variant have name, namespaces, and params (for generics) where then would
you store the arguments?

2022-07-27 18:32 UTC, adleroliveira commented
Did a complete refactor of this and will open a new PR. Closing this one.

2022-07-27 18:32 UTC, closed without merging